import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] })
const page = await b.newPage({ viewport: { width: 1600, height: 900 } })
page.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
await page.goto('http://localhost:4173/?p=built&v=false&u=0&a=paid&i=dh-free&d=staging&t=22&c=640', { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.removeItem('remixer-prototype/world/v6'))
await page.waitForTimeout(400); await page.click('.home-card-face')
await page.waitForSelector('.boot-cover', { state: 'detached', timeout: 20000 })
await page.waitForSelector('[data-ve-bar]'); await page.waitForTimeout(800)
const bb = await (await page.$('[data-ve-bar]')).boundingBox()
await page.mouse.move(bb.x + 20, bb.y + 20); await page.waitForTimeout(600)
await page.click('[data-ve-dock-to-rail]'); await page.waitForTimeout(1500)
await page.screenshot({ path: 'scratchpad/edit-dock/shots/dbg0.png' })
const db = await (await page.$('[data-ve-dock]')).boundingBox()
await page.mouse.move(db.x + 24, db.y + 24); await page.waitForTimeout(800)
console.log('after move', await page.evaluate(() => document.querySelector('[data-ve-dock]')?.getAttribute('aria-expanded')))
await page.mouse.move(400, 400); await page.waitForTimeout(400)
await page.mouse.move(db.x + 24, db.y + 24); await page.waitForTimeout(800)
console.log('after second move', await page.evaluate(() => document.querySelector('[data-ve-dock]')?.getAttribute('aria-expanded')))
console.log(await page.evaluate(() => { const h = document.querySelector('[data-ve-dock-host]'); return { host: h?.outerHTML.slice(0, 400), popped: !!document.querySelector('[data-ve-popped]'), bars: document.querySelectorAll('[data-ve-bar]').length, expanded: document.querySelector('[data-ve-dock]')?.getAttribute('aria-expanded') } }))
await page.screenshot({ path: 'scratchpad/edit-dock/shots/dbg.png' })
await b.close()
