import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] })
const page = await b.newPage({ viewport: { width: 1600, height: 900 } })
const sc = async (l) => console.log(l, await page.evaluate(() => ({ y: scrollY, sh: document.documentElement.scrollHeight, bodySh: document.body.scrollHeight, scrolled: [...document.querySelectorAll('*')].filter((e) => e.scrollTop > 0 || e.scrollLeft > 0).map((e) => e.tagName + '.' + String(e.className).slice(0, 40) + ':' + e.scrollTop + '/' + e.scrollLeft).slice(0, 6) })))
await page.goto('http://localhost:4173/?p=built&v=false&u=0&a=paid&i=dh-free&d=staging&t=22&c=640', { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.removeItem('remixer-prototype/world/v6'))
await page.waitForTimeout(400); await page.click('.home-card-face')
await page.waitForSelector('.boot-cover', { state: 'detached', timeout: 20000 })
await page.waitForSelector('[data-ve-bar]'); await page.waitForTimeout(800)
await sc('start')
const bb = await (await page.$('[data-ve-bar]')).boundingBox()
await page.mouse.move(bb.x + 20, bb.y + 20); await page.waitForTimeout(700); await sc('hover')
await page.mouse.move(bb.x + 20, bb.y - 200); await page.waitForTimeout(450); await sc('leave')
await page.mouse.move(bb.x + 20, bb.y + 20); await page.waitForTimeout(500); await sc('hover2')
await page.click('[data-ve-dock-to-rail]'); await sc('click'); await page.waitForTimeout(1600); await sc('landed')
await b.close()
