import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] })
const page = await b.newPage({ viewport: { width: 1600, height: 900 } })
await page.goto('http://localhost:4173/?p=built&v=false&u=0&a=paid&i=dh-free&d=staging&t=22&c=640', { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.removeItem('remixer-prototype/world/v6'))
await page.waitForTimeout(400); await page.click('.home-card-face')
await page.waitForSelector('.boot-cover', { state: 'detached', timeout: 20000 })
await page.waitForSelector('[data-ve-bar]'); await page.waitForTimeout(800)
const bb = await (await page.$('[data-ve-bar]')).boundingBox()
await page.mouse.move(bb.x + 20, bb.y + 20); await page.waitForTimeout(1200)
console.log(await page.evaluate(() => { const h = document.querySelector('[data-ve-dock-to-rail]'); const r = h.getBoundingClientRect(); const p = h.closest('[data-ve-bar]').getBoundingClientRect(); return { handle: [r.x, r.y, r.width, r.height], pill: [p.x, p.y, p.width, p.height], shell: document.querySelector('.flex.h-full.overflow-hidden').scrollTop } }))
await page.evaluate(() => document.querySelector('[data-ve-dock-to-rail]').scrollIntoView({ block: 'nearest', inline: 'nearest' }))
console.log('after nearest', await page.evaluate(() => document.querySelector('.flex.h-full.overflow-hidden').scrollTop))
await page.evaluate(() => document.querySelector('[data-ve-dock-to-rail]').scrollIntoViewIfNeeded && document.querySelector('[data-ve-dock-to-rail]').scrollIntoViewIfNeeded())
console.log('after ifNeeded', await page.evaluate(() => document.querySelector('.flex.h-full.overflow-hidden').scrollTop))
await b.close()
