import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] })
const page = await b.newPage({ viewport: { width: 1600, height: 900 } })
page.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
await page.goto('http://localhost:4173/?p=built&v=false&u=0&a=paid&i=dh-free&d=staging&t=22&c=640', { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.removeItem('remixer-prototype/world/v6'))
await page.waitForTimeout(400); await page.click('.home-card-face')
await page.waitForSelector('.boot-cover', { state: 'detached', timeout: 20000 })
await page.waitForSelector('[data-ve-bar]'); await page.waitForTimeout(800)
const st = () => page.evaluate(() => { const g = document.querySelector('[data-ve-glass]'); const tail = document.querySelector('[data-ve-dock-to-rail]').parentElement; return { stretched: document.querySelector('[data-ve-bar]').hasAttribute('data-ve-stretched'), glassStyle: g.getAttribute('style'), glassW: g.getBoundingClientRect().width, tailLeft: tail.style.left, tailW: tail.offsetWidth, tailOpacity: getComputedStyle(tail).opacity } })
console.log('rest', await st())
const bb = await (await page.$('[data-ve-bar]')).boundingBox()
await page.mouse.move(bb.x + 20, bb.y + 20); await page.waitForTimeout(300); console.log('hover300', await st()); await page.waitForTimeout(800); console.log('hover1100', await st())
await b.close()
