import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME })
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
await p.goto('http://localhost:4173/?p=built&a=paid&d=ready&n=fit-ration.com&v=true&u=0&t=22&c=640', { waitUntil: 'networkidle' })
await p.waitForTimeout(800); await p.click('.home-card-face'); await p.waitForSelector('.boot-cover', { state: 'detached', timeout: 15000 }); await p.waitForTimeout(400)
await p.click('header button:has-text("Publish")'); await p.waitForTimeout(1200)
const probe = (label) => p.evaluate((label) => new Promise((r) => { const t = setTimeout(() => r(label + ': raf silent 1000ms, visibility=' + document.visibilityState), 1000); requestAnimationFrame(() => { clearTimeout(t); r(label + ': raf ok') }) }), label)
console.log(await probe('before click'))
await p.evaluate(() => { const d = document.querySelector('[role="dialog"][aria-label="Publish"]'); [...d.querySelectorAll('button')].find((b) => /^Publish to/.test(b.textContent.trim())).click() })
console.log(await probe('right after click'))
await p.waitForTimeout(500)
console.log(await probe('500ms later'))
const h = await p.evaluate(() => { const d = document.querySelector('[role="dialog"][aria-label="Publish"]'); return { h: d.getBoundingClientRect().height, title: d.querySelector('h3')?.textContent, busy: !!d.querySelector('button[aria-busy]') } })
console.log(JSON.stringify(h))
await p.waitForTimeout(2200)
console.log(await probe('after beat'))
console.log(JSON.stringify(await p.evaluate(() => { const d = document.querySelector('[role="dialog"][aria-label="Publish"]'); return { h: d.getBoundingClientRect().height, title: d.querySelector('h3')?.textContent, busy: !!d.querySelector('button[aria-busy]') } })))
await b.close()
