import { chromium } from 'playwright'
const BASE = 'http://localhost:5174'
const b = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] })
const ctx = await b.newContext({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 3 })
const p = await ctx.newPage()
await p.goto(`${BASE}?p=built&v=true&u=0&a=paid&i=dh-free&d=staging&t=22&c=640`, { waitUntil: 'networkidle' })
await p.waitForTimeout(700)
await p.click('.home-card-face')
await p.waitForSelector('.boot-cover', { state: 'detached', timeout: 20000 })
await p.waitForTimeout(600)
const rail = await p.$('nav.arrive-rail')
await rail.screenshot({ path: '/tmp/rail-rest.png' })
await p.click('nav.arrive-rail [aria-label="Cloud"]')
await p.waitForTimeout(900)
await rail.screenshot({ path: '/tmp/rail-selected.png' })
await p.hover('nav.arrive-rail [aria-label="Analytics"]')
await p.waitForTimeout(400)
await rail.screenshot({ path: '/tmp/rail-hover.png' })
await p.mouse.move(800, 800)
await p.waitForTimeout(300)
await p.screenshot({ path: '/tmp/cloud-final.png' })
await b.close()
