/** Why does Escape not close the Image panel? Opens it, presses Escape, reports. */
import { chromium } from 'playwright'
const BASE = process.env.BASE || 'http://localhost:4173/'
const browser = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] })
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } })
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log('CONSOLE', m.type(), m.text().slice(0, 200)) })
page.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await page.goto(BASE + '?p=built&v=false&u=0&a=paid&i=dh-free&d=staging&t=22&c=640', { waitUntil: 'networkidle' })
await page.waitForTimeout(700)
await page.click('.home-card-face')
await page.waitForSelector('.boot-cover', { state: 'detached', timeout: 20000 })
await page.waitForTimeout(500)
await page.click('[data-ve-tool="edit"]')
await page.waitForTimeout(400)
const photo = await page.$('[data-edit="meal.power-bowl.photo"]')
await photo.scrollIntoViewIfNeeded()
await photo.click()
await page.waitForSelector('[data-ve-image-panel]')
await page.waitForTimeout(600)
console.log('active before Esc:', await page.evaluate(() => { const e = document.activeElement; return e ? e.tagName + ' ' + (e.className || '').toString().slice(0, 60) + ' ce=' + e.isContentEditable : null }))
await page.evaluate(() => { window.addEventListener('keydown', (e) => console.warn('KEY seen at window capture', e.key, 'defaultPrevented', e.defaultPrevented), true) })
await page.keyboard.press('Escape')
await page.waitForTimeout(400)
console.log('panel after Esc:', !!(await page.$('[data-ve-image-panel]')))
console.log('tool after Esc:', await page.$eval('[data-ve-tool="edit"]', (e) => e.getAttribute('aria-pressed')))
// second Escape
await page.keyboard.press('Escape')
await page.waitForTimeout(400)
console.log('panel after 2nd Esc:', !!(await page.$('[data-ve-image-panel]')), 'tool:', await page.$eval('[data-ve-tool="edit"]', (e) => e.getAttribute('aria-pressed')))
await page.screenshot({ path: new URL('./shots/esc.png', import.meta.url).pathname })
await browser.close()
