/** The Select tool: pick the hero title, see the chip in the composer, send, see the chip in the bubble. */
import { chromium } from 'playwright'
import { mkdirSync } from 'node:fs'
const BASE = process.env.BASE || 'http://localhost:4173/'
const OUT = new URL('./shots/', import.meta.url).pathname
mkdirSync(OUT, { recursive: true })
const browser = await chromium.launch({ executablePath: process.env.CHROME, args: ['--no-sandbox'] })
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } })
page.on('pageerror', (e) => console.log('PAGEERROR', e.message))
await page.goto(BASE + '?p=built&v=false&u=0&a=paid&i=dh-free&d=staging&t=22&c=640', { waitUntil: 'networkidle' })
await page.waitForTimeout(700)
await page.click('.home-card-face')
await page.waitForSelector('.boot-cover', { state: 'detached', timeout: 20000 })
await page.waitForTimeout(500)
await page.click('[data-ve-tool="select"]')
await page.waitForTimeout(400)
console.log('select pressed:', await page.$eval('[data-ve-tool="select"]', (e) => e.getAttribute('aria-pressed')))
const title = await page.$('[data-pick="home.hero.title"]')
console.log('title has data-pick:', !!title)
await title.hover(); await page.waitForTimeout(200)
console.log('hover ring:', !!(await page.$('.ve-ring--hover')))
await title.click()
await page.waitForTimeout(400)
console.log('pinned ring:', !!(await page.$('.ve-ring--pinned')), 'chip on site:', await page.$eval('[data-ve-chip]', (e) => e.textContent).catch(() => 'none'))
console.log('composer chip:', await page.$eval('[data-about-chip]', (e) => e.textContent).catch(() => 'none'))
console.log('placeholder:', await page.$eval('textarea', (e) => e.getAttribute('placeholder')))
console.log('focused textarea:', await page.evaluate(() => document.activeElement?.tagName))
await page.screenshot({ path: OUT + 's1-picked.png' })
await page.fill('textarea', 'Make it shorter')
await page.keyboard.press('Enter')
await page.waitForTimeout(900)
console.log('bubble about:', await page.$$eval('[data-about]', (els) => els.map((e) => e.textContent)))
console.log('composer chip after send:', !!(await page.$('[data-about-chip]')))
await page.screenshot({ path: OUT + 's2-sent.png' })
await browser.close()
